function Hd = IIR_notch
%IIR_NOTCH Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 28-Mar-2023 19:08:34

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 200;  % Sampling Frequency

Fnotch = 50;  % Notch Frequency
Q      = 35;  % Q-factor
Apass  = 3;   % Bandwidth Attenuation

BW = Fnotch/Q;

% Calculate the coefficients using the IIRNOTCHPEAK function.
[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
